# Generated by Django 4.0.3 on 2022-03-30 09:20

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Telegram user id"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Telegram username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=64,
                        verbose_name="First name",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=64,
                        verbose_name="Last name",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
    ]
