# Generated by Django 4.0.3 on 2022-03-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='RecipeIngredientAmount',
        ),
    ]
