# Generated by Django 4.0.3 on 2022-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Calories'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Carbohydrates'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Proteins'),
        ),
    ]
