# Generated by Django 4.0.3 on 2022-03-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_allergy_remove_subscription_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='recipes.allergy', verbose_name='Ingredient allergy'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='recipes.allergy', verbose_name='Subscription allergies list'),
        ),
    ]
