# Generated by Django 4.0.3 on 2022-04-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_promocode_subscription_promo_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['discount']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredientamount',
            options={'ordering': ['ingredient']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['telegram_id']},
        ),
    ]
