# Generated by Django 4.0.3 on 2022-04-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_image_remove_recipe_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subscription plan name')),
                ('price', models.PositiveIntegerField(verbose_name='Subscription plan price')),
                ('currency', models.CharField(choices=[('RUR', 'Russian ruble'), ('EUR', 'Euro'), ('USD', 'USD')], default='RUR', max_length=3)),
                ('duration', models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (6, 'Six'), (12, 'Twelve')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.subscriptionplan', verbose_name='Subscription plan'),
            preserve_default=False,
        ),
    ]
